SET DEFINE OFF
SET SQLBLANKLINES ON
WHENEVER SQLERROR EXIT SQL.SQLCODE

CREATE TABLE todos (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    titulo VARCHAR2(200) NOT NULL,
    descripcion CLOB,
    estado VARCHAR2(20) DEFAULT 'pendiente' NOT NULL,
    prioridad VARCHAR2(20) DEFAULT 'media' NOT NULL,
    fecha_creacion TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    fecha_actualizacion TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    fecha_vencimiento TIMESTAMP NULL,
    fecha_completada TIMESTAMP NULL,
    usuario_id NUMBER NULL,
    CONSTRAINT pk_todos PRIMARY KEY (id),
    CONSTRAINT ck_todos_estado
        CHECK (estado IN ('pendiente', 'en_progreso', 'completada', 'cancelada')),
    CONSTRAINT ck_todos_prioridad
        CHECK (prioridad IN ('baja', 'media', 'alta')),
    CONSTRAINT ck_todos_titulo_no_vacio
        CHECK (TRIM(titulo) IS NOT NULL),
    CONSTRAINT ck_todos_fechas
        CHECK (fecha_vencimiento IS NULL OR fecha_vencimiento >= fecha_creacion),
    CONSTRAINT ck_todos_fecha_completada
        CHECK (
            (estado = 'completada' AND fecha_completada IS NOT NULL)
            OR (estado <> 'completada' AND fecha_completada IS NULL)
        )
);

CREATE INDEX idx_todos_estado ON todos (estado);
CREATE INDEX idx_todos_prioridad ON todos (prioridad);
CREATE INDEX idx_todos_usuario_id ON todos (usuario_id);
CREATE INDEX idx_todos_fecha_vencimiento ON todos (fecha_vencimiento);
CREATE INDEX idx_todos_estado_prioridad ON todos (estado, prioridad);

CREATE OR REPLACE TRIGGER trg_todos_fechas
BEFORE INSERT OR UPDATE ON todos
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.fecha_creacion := COALESCE(:NEW.fecha_creacion, SYSTIMESTAMP);
        :NEW.fecha_actualizacion := COALESCE(:NEW.fecha_actualizacion, :NEW.fecha_creacion);
    ELSE
        :NEW.fecha_actualizacion := SYSTIMESTAMP;
    END IF;

    IF :NEW.estado = 'completada' AND (INSERTING OR :OLD.estado <> 'completada') THEN
        :NEW.fecha_completada := SYSTIMESTAMP;
    ELSIF :NEW.estado <> 'completada' THEN
        :NEW.fecha_completada := NULL;
    END IF;
END;
/

COMMENT ON TABLE todos IS 'Tabla para registrar tareas o TODOs';
COMMENT ON COLUMN todos.id IS 'Identificador unico de la tarea';
COMMENT ON COLUMN todos.titulo IS 'Titulo corto de la tarea';
COMMENT ON COLUMN todos.descripcion IS 'Descripcion detallada de la tarea';
COMMENT ON COLUMN todos.estado IS 'Estado actual: pendiente, en_progreso, completada, cancelada';
COMMENT ON COLUMN todos.prioridad IS 'Prioridad: baja, media, alta';
COMMENT ON COLUMN todos.fecha_creacion IS 'Fecha de creacion de la tarea';
COMMENT ON COLUMN todos.fecha_actualizacion IS 'Fecha de la ultima actualizacion';
COMMENT ON COLUMN todos.fecha_vencimiento IS 'Fecha limite de la tarea';
COMMENT ON COLUMN todos.fecha_completada IS 'Fecha en que la tarea fue marcada como completada';
COMMENT ON COLUMN todos.usuario_id IS 'Referencia opcional al usuario duenio de la tarea';
