SET DEFINE OFF
SET SQLBLANKLINES ON
WHENEVER SQLERROR EXIT SQL.SQLCODE

CREATE TABLE usuarios (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    nombre VARCHAR2(120) NOT NULL,
    email VARCHAR2(254) NOT NULL,
    password_hash VARCHAR2(255) NOT NULL,
    activo NUMBER(1) DEFAULT 1 NOT NULL,
    fecha_creacion TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    fecha_actualizacion TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT pk_usuarios PRIMARY KEY (id),
    CONSTRAINT ck_usuarios_activo CHECK (activo IN (0, 1)),
    CONSTRAINT ck_usuarios_nombre_no_vacio CHECK (TRIM(nombre) IS NOT NULL),
    CONSTRAINT ck_usuarios_email_no_vacio CHECK (TRIM(email) IS NOT NULL)
);

CREATE UNIQUE INDEX ux_usuarios_email_lower ON usuarios (LOWER(email));

CREATE OR REPLACE TRIGGER trg_usuarios_fechas
BEFORE INSERT OR UPDATE ON usuarios
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.fecha_creacion := COALESCE(:NEW.fecha_creacion, SYSTIMESTAMP);
        :NEW.fecha_actualizacion := COALESCE(:NEW.fecha_actualizacion, :NEW.fecha_creacion);
    ELSE
        :NEW.fecha_actualizacion := SYSTIMESTAMP;
    END IF;
END;
/

CREATE TABLE refresh_tokens (
    id RAW(16) DEFAULT SYS_GUID(),
    usuario_id NUMBER NOT NULL,
    token_hash VARCHAR2(64) NOT NULL,
    expires_at TIMESTAMP NOT NULL,
    revoked_at TIMESTAMP NULL,
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    replaced_by_token_id RAW(16) NULL,
    user_agent VARCHAR2(400) NULL,
    ip_address VARCHAR2(64) NULL,
    CONSTRAINT pk_refresh_tokens PRIMARY KEY (id),
    CONSTRAINT fk_refresh_tokens_usuario
        FOREIGN KEY (usuario_id) REFERENCES usuarios (id) ON DELETE CASCADE,
    CONSTRAINT fk_refresh_tokens_replaced_by
        FOREIGN KEY (replaced_by_token_id) REFERENCES refresh_tokens (id)
);

CREATE UNIQUE INDEX ux_refresh_tokens_hash ON refresh_tokens (token_hash);
CREATE INDEX idx_refresh_tokens_usuario_id ON refresh_tokens (usuario_id);
CREATE INDEX idx_refresh_tokens_expires_at ON refresh_tokens (expires_at);

COMMENT ON TABLE usuarios IS 'Usuarios que pueden iniciar sesion en la aplicacion';
COMMENT ON COLUMN usuarios.password_hash IS 'Hash de la contrasenia; nunca guardar la contrasenia en texto plano';
COMMENT ON TABLE refresh_tokens IS 'Refresh tokens persistidos como hash para renovar sesiones sin guardar el token real';
COMMENT ON COLUMN refresh_tokens.token_hash IS 'SHA-256 del refresh token; el token real solo vive en el cliente';
COMMENT ON COLUMN refresh_tokens.revoked_at IS 'Fecha en que el refresh token dejo de ser valido';
